# Generated by Django 4.2.7 on 2023-12-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_organisation_agent_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='user',
            new_name='owner',
        ),
    ]
